apiVersion: v1
kind: Service
metadata:
  name: resonance-server
  labels:
    app: resonance-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: resonance-server
---
apiVersion: v1
kind: Service
metadata:
  name: resonance-server-headless
  labels:
    app: resonance-server
spec:
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: resonance-server
